### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by haisenberg** [Healix/Gw2Launcher#1]
Hi Healix,
I tried to set up everything accordingly to what you have written in the README. Still, the launcher refuses to open more than one client. I want to run two clients. I have a main windows user account and another created by your tool. The launcher created the local.dat file in every respective roaming folder of each user account properly. When I try to start a client, it get prompted with the "new local.dat"-file notification for whatever reason. In the event that one client launched successfully, I cannot launch another client. I get a notification that the GW2 data file is already in use (or just nothing just "failed"). UAC is deactivated (lowest possible settings) on my system. Do I have to login with the windows account at least ones? Did I miss something crucial?

Regards ;>

**Comment by Healix** [comment]
When launching an account for the first time, you are you are asked if you would like to launch "normally" in order to modify your settings, since they become read-only otherwise. Is this the "new local.dat" message you meant? When selected to launch normally, GW2 can only be opened once and any further launches are queued, waiting for the first to close.

What is saying the "GW2 data file" is already in use? Do you mean Local.dat or Gw2.dat? GW2 will display the error "archive already in use" (Gw2.dat) if you try to launch GW2 more than once normally. If Local.dat was the problem, ensure that each account is assigned the proper file. Right click an account, select edit, then choose Local.dat on the left side. Click the "..." button for file options, the simplest being to create a new file. If you've selected to share a Local.dat file, note that each account must use the same Windows user account, otherwise you'll get the "unable to move" error.

You shouldn't need to login to a Windows user account yourself since it's automatically done by Windows in the background when attempting to use it.

Just in case, if you've launched GW2 by directly executing Gw2.exe/Gw2-64.exe, you can't do that since it'll lock Gw2.dat.

If you are using the 32-bit version, try re-downloading it. I made changes to the 64-bit version a while back, but never updated the 32-bit version. I don't recall exactly what they were, but I've recompiled the 32-bit version, which may help.

**Comment by haisenberg** [comment]
>
>When launching an account for the first time, you are you are asked if you would like to launch >"normally" in order to modify your settings, since they become read-only otherwise. Is this the "new >local.dat" message you meant? When selected to launch normally, GW2 can only be opened once >and any further launches are queued, waiting for the first to close.

I see. Yes, I am talking about the about this notification.


> What  is saying the "GW2 data file" is already in use? Do you mean Local.dat or Gw2.dat? GW2 will display the error "archive already in use" (Gw2.dat) if you try to launch GW2 more than once normally. If Local.dat was the problem, ensure that each account is assigned the proper file. Right click an account, select edit, then choose Local.dat on the left side. Click the "..." button for file options, the simplest being to create a new file. If you've selected to share a Local.dat file, note that each account must use the same Windows user account, otherwise you'll get the "unable to move" error.

I am talking about gw2.dat; the archive. Files are correctly assigned.

> You shouldn't need to login to a Windows user account yourself since it's automatically done by Windows in the background when attempting to use it.

Ok.

> Just in case, if you've launched GW2 by directly executing Gw2.exe/Gw2-64.exe, you can't do that since it'll lock Gw2.dat.

I did.. and this seems to be the issue here. I want to clients running at the same time. This means I have to copy the at least the gw2.dat and create another one? I try reloading the compiled files, I used the x64 version.

**Comment by Healix** [comment]
Any accounts you want to run simultaneously must be setup and launched using this tool. You should not be trying to execute Gw2.exe/Gw2-64.exe directly. 

To add another account, hold alt or right click an existing account and select to create a new account. Give the account an identifier/name and you can leave the user blank to indicate your current user account. For the Local.dat, select to move an existing file and choose your original one (%appdata%/Guild Wars 2/Local.dat). Click OK to create the account, or set any of the other options you want.

If for whatever reason you absolutely want to run your main account directly, you can do so by adding the -sharearchive option to the shortcut of GW2. Note that this option makes the game read-only, so you'll need to remove it any time the game needs to update.
