### ISSUE TITLE
Program:Win32/Uwamson.A!ml

### ISSUE THREAD

**Issue by UniversityDepression** [Healix/Gw2Launcher#103]
Hi both Windows Security and Avast flag Gw2Launcher.exe as Program:Win32/Uwamson.A!ml, never had issues with Gw2Launcher before.

Affected Items:
containerfile: C:\Users\Administrator\AppData\Local\Google\Chrome\User Data\Default\Cache\f_0002b6

file: C:\Users\Administrator\AppData\Local\Google\Chrome\User Data\Default\Cache\f_0002ff

file: C:\Users\Administrator\AppData\Local\Google\Chrome\User Data\Default\Cache\f_0002b6->Gw2Launcher-master/Gw2Launcher/bin/Release/Gw2Launcher.exe

**Comment by Healix** [comment]
Judging by the affected files, you're trying to download the release build? It hasn't been changed since September and that just added support for the DX11 changes. The build before that was nearly a year ago.

Uwamson.A!ml is detection via machine learning, so it's entirely guesswork - this program may do something you may not want it to do. It could be something as trivial as the fact that Gw2Launcher accesses system files or can update itself. There are some features however that once enabled, will definitely trigger anti-virus software, such as the asset proxy or user account management.
