### ISSUE TITLE
Install cannot be completed

### ISSUE THREAD

**Issue by artsaraiva** [Healix/Gw2Launcher#107]
Whenever I try to open more then one account at the same time, only the first one logs in and the rest shows this error:
![Sem título](https://user-images.githubusercontent.com/21348329/145753445-c731c9c7-481f-431e-bd6a-3878567ab082.png)
Am I doing something wrong? I have no addons
![Sem título](https://user-images.githubusercontent.com/21348329/145753536-d8498974-a299-4313-8676-7f9bf99839ca.png)

**Comment by Healix** [comment]
I'm assuming all accounts can be launched if you only launch one at a time? I've only heard of this happening with addons, specifically d912pxy would cause this error. Are you sure you're not using addons? If you previously had addons and removed them from the bin64 folder, they may still be found under each account's bin64 folder - click resync to reset it (or delete the Gw2Launcher folder where Gw2-64.exe is located)

Try disabling localized execution. If it's still a problem, try using basic mode. If it's still a problem, open the Guild Wars 2 folder (where Gw2-64.exe is located) and delete everything except Gw2.dat (~50GB) and Gw2-64.exe (~37MB), then right click any account > All > Update.

If it's still a problem, it's likely caused by other software. d912pxy caused this because it was requiring an exclusive lock, which meant only 1 account could be active at a time. You likely have something hooking into GW2 and doing something similar.

**Comment by artsaraiva** [comment]
launching each account individually does work. Once I get back from work I will test what you suggested. Just to note I was using mods (arcdps, d912pxy and gw2 radial) but deleted all of them and reinstalled the game to check if that did the trick but unfortunately it didn't

**Comment by artsaraiva** [comment]
did some testing around and apparently I can use multiple accounts at the same time if I wait each to launch first then launch the next one. Using the All/Selected > Launch gives the error. Something about multiple logins at the same time maybe. Tried everything you mentioned but no luck

**Comment by Healix** [comment]
You could enable a delay when launching multiple accounts (Settings > General > Launching).

Other than that, you could try running GW2 as an admin by starting Gw2Launcher as an admin (right click the exe > run as admin), which would prevent non-admin programs from interfering, but chances are it's also running as an admin.

For a simple test, run the beta version:
https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe
This is just to check if it has anything to do with file links or the name of the executable. Note this will automatically set localized execution to full. Right click the top-right X button for a menu. Select "enable copy only", then "initialize". Try launching accounts to trigger the problem. If it's still a problem, also select "enable rename", then "initialize" again. Try it again. If either of these happens to solve it, do it again to confirm it and whether one or both are required. If neither helps, there's nothing else I could do, as it would be a lock on something outside of my control. When you're done, uncheck both options, then initialize to reset it.

**Comment by artsaraiva** [comment]
I've put a 30 sec delay and now it works perfectly. Also running with window mode helps too. Ty for the help!
