### ISSUE TITLE
YoloMouse not active from launch

### ISSUE THREAD

**Issue by EnergyAura** [Healix/Gw2Launcher#13]
After setting up YoloMouse with each account created, relaunching does not activate YoloMouse. Not sure if this is a GW2Launcher issue, but YoloMouse functioned correctly in previous versions of GW2Launcher and YoloMouse has no updates since those releases.

**Comment by Healix** [comment]
I took a quick look and the problem was, YoloMouse is reading its settings from one file but writing it to another. YoloMouse the EXE looks for its settings in your standard local appdata folder. If it doesn't exist, it won't load. YoloMouse the DLL however saves its settings in GW2's local appdata folder.

This was actually always a problem, you could just avoid it by having a file in the location the EXE was looking for, which would then cause it to load the DLL along with its saved settings.

I've added a fix for this in the recent build.
