### ISSUE TITLE
unable to add 4th account

### ISSUE THREAD

**Issue by gunnho** [Healix/Gw2Launcher#16]
i use 3 alt accounts successfully with your program and and enjoy it. 

however i bought a 4th account and for some reason i just cant seem to add it successfully. i make a 4th account tab, give it a unique name, add a new local.dat and it fails. i get your error poup about shared file not writeable.

so i try again but copy from an existing and launch normal, i type in the new account details, click remember login off and on again, get your own error popup. 

delete tab, create a new one, create new local.dat, select/update, select/launch normal, type in details, start game. turn off and launch again, details are blank and not remembered.

i followed your wiki but nothing in there tells me what the problem might be

**Comment by Healix** [comment]
To simplify, right click the account > edit > select the Local.dat tab > ... > Create a new Local.dat file > OK. 

Under the Launch Options tab, scroll to the bottom and look for screenshots. Try to check the box under "change where screenshots are saved". If you can't, let me know. Leave it unchecked if you weren't already using it.

OK out of the options, right click the account > selected > Launch (normal). If there's an error, write the exact message.

**Comment by gunnho** [comment]
created a new tab, selected new local.dat (starts in tmp folder) then it created a new/10/local.dat file (had previously 7, 8, 9 local.dat previously). selected/launch normal. gets the following error (and yes i updated to the most recent version today before trying this)

unable to open archive file

guild wars 2 is unable to open its archive file, please very that this file is accessible and writable and that no other program is currently using it

**Comment by Healix** [comment]
Close Gw2Launcher if it's open, and any active accounts, then open any folder and enter the following into the address bar and press enter:
%appdata%/Gw2Launcher

In the folder should be a "data" folder. Rename it to "data1", then start Gw2Launcher. Once it's started, the "data" folder should be re-created. Within the "data1" folder should be #.dat and #.xml files. Move these files from "data1" to "data", but don't copy any of the folders. There should currently be no other folders in the "data" folder - if there are, delete them. You can delete the "data1" folder.

Confirm it's still a problem. The above should have only had an effect if something else has modified the folders.

Right click the account > edit > Local.dat. Confirm the path ends with Gw2Launcher\data\\#.dat (if ends with tmp, launch the account). In the "data" folder, confirm #.dat exists. In Gw2Launcher, select the statistics tab and look at the ID, then in the "data" folder, open the folder with this ID and follow its sub-folders to AppData\Roaming\Guild Wars 2\. In this folder should be Local.dat. Delete it, then right click the account > selected > update. Confirm whether Local.dat is re-created or not. If it's not, GW2's open archive error should tell you the path of Local.dat - confirm it's the same as the Local.dat you just deleted.

Generally, GW2 should only be unable to open its archive (when updating or launching in normal mode) when the file is either locked by another program (in which case you wouldn't be able to delete it) or it doesn't have permission. If you want to try forcing it, close Gw2Launcher, then right click it and run it as an administrator.

The screenshots folder I mentioned earlier was just a simple way to test which method Gw2Launcher is using. If you were unable to enable that feature, it means your computer doesn't support file linking, which forces Gw2Launcher to use an alternative method and rather than using the "data" folder, it'll use "data\alt".

**Comment by gunnho** [comment]
ok, i renamed data to data1, moved the numbered folders to a new data, started launcher, created a new account, same error "unable to open archive file". closed launcher, then run as administrator, same error. selected "gw2launcher" folder, rightclick/properties and some folders were read only. i unticked and applied to all subfolders, run the account again, same error.

i noticed in the new data folder the dat file and xml file were 0 bytes

now in launcher, new account/selected/update and the dat/xml files now have data volume. the timestamp has updated. selected/launch normal started the patcher ui, i get the logon screen, i entered uname/pword, ticked remember/auto and the game launches to charselect screen, i exit to desktop, relaunch account and get the logon screen but it is blank, no uname/pword remembered.

i am logged into the my computer as administrator account, i run gw2launcher as admin. i am not sure what could be locking the gw2launcher folders/files as readonly.

**Comment by Healix** [comment]
Right click any account > settings > Launch options. Confirm you haven't added "sharearchive" to the arguments.

---

> i renamed data to data1, moved the numbered folders to a new data

You only wanted to move the numbered files. If the files in your data folder aren't 0 bytes, delete the folders.

> selected "gw2launcher" folder, rightclick/properties and some folders were read only

Note that all folders will show the read-only box with a square, whereas a check mark means it's actually read-only. It'll only matter if the files are read-only, specifically Local.dat/#.dat, which would cause GW2 to show the archive error.

> i noticed in the new data folder the dat file and xml file were 0 bytes

If the folder was already open, you need to refresh it or specifically view the properties of file to see its size. Windows is slow to show updates to these files because they're linked.

> selected/launch normal started the patcher ui, i get the logon screen, i entered uname/pword, ticked remember/auto and the game launches to charselect screen, i exit to desktop, relaunch account and get the logon screen but it is blank, no uname/pword remembered

To be clear, you're launching with the "launch (normal)" option, otherwise GW2 won't save your settings. As a little test, "launch (normal)" and check "AUTO-PLAY" on GW2's launcher, then close GW2 by clicking its X. Launch it again. Did it remember? If it's just the email/password not being remembered, that a problem involving your user.

> i am logged into the my computer as administrator account, i run gw2launcher as admin.

There is an actual "Administrator" account, then there are normal users in the administrators group. To be clear, although you're an administrator, you still have to specifically choose to run something with administrator privileges, unless that's been disabled.

**Comment by gunnho** [comment]
i fixed it, i went to %appdata%/gw2launcher and deleted it completely, restarted gw2launcher from scratch and entered each account one by one and started each one with their details. only then could i launch all accounts at the same time perfectly. thank you for taking the time to reply with my issue, youre doing a wonderful job, and frankly, since the anet change your tool is so much better than launchbuddy with a cleaner interface
