### ISSUE TITLE
GW2 instances sometimes crash on Login

### ISSUE THREAD

**Issue by charlesember** [Healix/Gw2Launcher#170]
Hello Healix,

Thank you for maintaining the gw2Launcher :3

With the latest beta launcher, i have encoutered a bug - which probably is related to the Launcher.
I generally login 3 accounts at a time to get daily rewards
On some occasions when the main (game) window launches - then it crashes.
so the general chain is like:
gw2Launcher launches the login screen -> logs in -> login screen closes -> main (full) screen launches -> main screen crashes

Using the beta branch is the first time that i encountered these issues - so i think it is related to the GW2Launcher and not to the proprietary Gw2 Launcher.

If you need any more information please let me know

Sincereley
Charlie

**Comment by Healix** [comment]
Is the game showing the error report window - what is the reason given for the crash? If not, when it crashes, is the game exiting, or not responding.

**Comment by charlesember** [comment]
The crash is basically the game not responding anymore - so there is no special error code submitted
It is the classis "GW2.exe does not respond"

**Comment by Healix** [comment]
Was that not a problem before? Were you able to launch multiple accounts multiple times with the previous version?

GW2 introduced a bug in the Dragonbash patch that could cause the game to freeze prior to character select. It was a rare occurrence normally, but I could reliably trigger it (without using Gw2Launcher) by having another game loading at the same time (I tested it just now and can confirm it's still a problem). After the recent patch that made GW2 slower to initialze, it has been _a lot_ more common for me.

**Comment by charlesember** [comment]
Previously i was able to launch 3 accounts at the same time - using the "Delay until the main window is loaded" function

so i dont think that would be the issue

**Comment by Healix** [comment]
Was "previously" after the Clockwork (July 19) patch / can you still reliably use the old version to launch multiple accounts?

Once play is clicked on the launcher, there's isn't really any difference between the beta and the old version; the changes were for the launcher/login. There was a flaw due to the patch (it potentially wouldn't wait until the main window was actually loaded), but that would have applied to all versions (fixed ~2 days ago).

I did a lot of experimenting and found that prioritizing GW2 while it's loading can help. I've included that into the [beta version](https://github.com/Healix/Gw2Launcher/tree/master/Gw2Launcher/bin64/Beta), and as a backup, it will also automatically relaunch an account that takes too long to load.

**Comment by charlesember** [comment]
The bug / the issue started arising, when i swapped to the beta branch - that was on the 20/07 - since the logins are still not working on the release branch

I cant test it on the release branch - since the login fields dont get filled with the login information

**Comment by charlesember** [comment]
Small update

The problem seems to have been fixed - maybe it is  due to the mentioned fix

> There was a flaw due to the patch (it potentially wouldn't wait until the main window was actually loaded), but that would have applied to all versions (fixed ~2 days ago).

Thank you very much for the support 😄 

Charlie
