### ISSUE TITLE
Can't use backup file and auto login is not working

### ISSUE THREAD

**Issue by aybarsorm** [Healix/Gw2Launcher#218]
Hi, I change my computer and I want to carry my accounts with an old .bkp file but I don't know how to. I enter one of them by hand and auto login is not working. It just opens the game launcher window and doesn't enter my account. All of my accounts are old ArenaNet accounts and I downloaded the game from Steam. Can you help?

**Comment by Healix** [comment]
It sounds like you were but are currently not using the [beta version](https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe).

Backups are a new feature in the beta version and are restored under Settings > Backup. Click restore and select a backup file, which will show some information about what's in the backup and give you the option to restore it.

Automatic logins in the release version will fail on some systems due to the problems with the new version of CoherentUI that GW2 switched to back in July. If the beta version isn't working, right click any account > Tools > Log, then try launching an account to see where it's getting stuck.

**Comment by aybarsorm** [comment]
thank you so much ^^
