### ISSUE TITLE
Risk of VAC or other anti cheat bans?

### ISSUE THREAD

**Issue by poggersmcgee** [Healix/Gw2Launcher#227]
Hey, 

I stream GW2 as well as a few other games on twitch. Generally, I tab back and forth between them depending on ranked queue down times and such. 

One of those games is CSGO, the another being Apex Legends.

Would the process running for this launcher have the risk of triggering a ban for VAC/EasyAntiCheat/etc if games utilizing them were run simultaneously with GW2Launcher? In a similar vein to an "oops, I left cheat engine running" sort of scenario. 

Appreciate any insight and apologies for a probably dumb question. 

Cheers, and thanks for the great work.

**Comment by Healix** [comment]
Gw2Launcher at its basic level just moves files and acts as a macro (if you use automatic logins). I've always avoided the riskier way of do things, like injecting addons, as I consider it against the rules and know it would trigger anti-cheat software if GW2 had any. Worst case, the most that should happen is your game wouldn't start due to running an unknown program, if the anti-cheat software was _that_ paranoid, but that's unrealistic.

**Comment by poggersmcgee** [comment]
> 

Thank you for the (extremely!) quick response, I appreciate it.
