### ISSUE TITLE
App crash while updating (game client 15/10/2019)

### ISSUE THREAD

**Issue by Wolfoly** [Healix/Gw2Launcher#23]
Hello,

The app just close when the client try to update local.dat.

So we can't update and can't use the app.

**Comment by Healix** [comment]
Check if a log is being created and post it:
%appdata%/Gw2Launcher/Gw2Launcher.log

If you haven't tried to update manually, right click one of your accounts > selected > update. If that crashes, try a another account with a different Local.dat file.

**Comment by Wolfoly** [comment]
Hello,
No log file :/

I tried yesterday and today to update manually with multiple account but crash everytime.

I found in %appdata%\Gw2Launcher\data\temp, 6 directories for my 6 accounts and everytime in the first directory I have a new directory gw2cache-..... . I think, if everything work fine, this directory is removed.

I tried to copy my local.dat (the original in  appdata GW2 directory) and replace all 6 .dat in GW2Launcher, but still want to do an update, maybe .xml have an old build version so the app want to update all accounts.

**Comment by Wolfoly** [comment]
Problem solved, I removed GW2Launcher directory in appdata, recreate all account and no more issue.

**Comment by Healix** [comment]
To confirm, what happens if you now right click > all > update? Does it work?

**Comment by Wolfoly** [comment]
You are right, if I update all or just one, the app close like before.

Still no log file. Maybe a setting to activate ?

**Comment by Healix** [comment]
The only real difference between launching and updating is the UI, so I'm guessing the problem is there. Try toggling the asset server proxy (right click any account > tools > asset server proxy), then updating. I doubt this will help, but it does slightly change how the update UI works, so it will at least rule it out.

**Comment by Wolfoly** [comment]
Enable local asset server proxy fix the problem for the update feature.

I tried it yesterday, maybe I did something wrong, I tried to enable and disable lot of things.

**Comment by Wolfoly** [comment]
yes

**Comment by Healix** [comment]
Try this (assuming 64-bit):
https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe

Disable the proxy and try to update. If it still crashes, ensure the proxy is still disabled, then right click any account > Debug > Disable PerfCounters, then try updating again.

**Comment by Wolfoly** [comment]
Hello,
So, I tried this beta launcher.
Without proxy -> crash.
Without proxy and PerfCounters -> OK

**Comment by Healix** [comment]
If the "disable PerfCounters" option worked, this isn't something I can fix, as it's a problem outside of Gw2Launcher. It's either a problem with Windows, or it could be security software that is killing Gw2Launcher, both of which would explain why there's no crash log.

If you want to try to fix a potential problem in Windows, follow:

https://support.microsoft.com/en-us/help/2554336/how-to-manually-rebuild-performance-counters-for-windows-server-2008-6

... in short, open a command prompt (cmd.exe) and enter:
> cd c:\windows\system32
> lodctr /R
> cd c:\windows\sysWOW64
> lodctr /R
> WINMGMT.EXE /RESYNCPERF

**Comment by Wolfoly** [comment]
Ok, thank you for your time and for all the explanations.
I tried to repair but no change, I'll search for other solution or juste enable proxy if this solution works. ;)

**Comment by Healix** [comment]
Using the proxy will avoid the problem, since it disables the use of the Performance Counters. I was only using them to show some form of activity while updating, which was obsoleted by the proxy.

Enabling the proxy is recommended. It can improve patching and allow you to download patches outside of the game (tools > background patching). If you're using multiple copies of Local.dat, it's also recommended to allow direct updates (settings > tools > Local.dat), and the cache option there will also slightly help.

**Comment by Healix** [comment]
The most recent build should avoid this problem. It's still a problem with Windows, but it should no longer take out Gw2Launcher with it.
