### ISSUE TITLE
All accounts disappeared after BSOD.

### ISSUE THREAD

**Issue by pro0digy** [Healix/Gw2Launcher#24]
After having a BSOD on my laptop all of my accounts got disappeared from GW2Launcher. Is there anything i can do to get them back or i have to add them again?

**Comment by Healix** [comment]
You'll need to add them again. If it was recoverable, it would have automatically done so. (there's only 1 backup; I'll add more to prevent this in the future)

If you want to recover the Local.dat files, they can be found under %appdata%\Gw2Launcher\data. If you don't, it would be best to delete that folder.

**Comment by Healix** [comment]
The most recent build will now create several backups. It will automatically recover using the latest working backup if something goes wrong, or if you want to manually recover one, they can be found under %appdata%\Gw2Launcher\backups\, which you would just rename to settings.dat and overwrite the original in the previous folder.

If it fails due a disk problem however, this isn't really going to help, since you'd want the backups on a different drive.
