### ISSUE TITLE
Other programs no longer starting after launching

### ISSUE THREAD

**Issue by mrmodius** [Healix/Gw2Launcher#247]
I usually have Blish HUD start with my main account using 'Launch Options > Run after launching', but this no longer seems to be working for me after updating to the latest release. I've tried removing it and readding it, but still no luck

**Comment by Healix** [comment]
When is it configured to start? (default is after launching)

One change I made is Gw2Launcher will now keep track of the program that was launched. If it's still running in the background after an account is exited, it won't be started the next time the account is launched. You can right click the account > Selected > Run... to see the programs or manually start them; active programs will be highlighted blue.

For a simple test, configure notepad (C:\Windows\System32\notepad.exe) to run after launching, then it'll be obvious if it works or not.

Other reasons why Blish specifically might not work is if you've changed the mumble link name and haven't given that name to Blish.

**Comment by mrmodius** [comment]
Hello, I have tried adding notepad.exe but unfortunately that is not working either. On the 'Right Click > Run' menu, blish hud seems to still be displayed even though it is not on the run list? Not sure what is going on
![Screenshot 2023-01-12 235729](https://user-images.githubusercontent.com/56196031/212206100-3bbfce25-5e9e-4175-8272-95e19ba1c337.png)
![Screenshot 2023-01-12 235710](https://user-images.githubusercontent.com/56196031/212206103-0a9b5012-cd0e-430e-b1b7-1de02ce22c51.png)
![Screenshot 2023-01-12 235743](https://user-images.githubusercontent.com/56196031/212206110-c16c4cd0-bb0f-4bea-91e0-f85b1319518c.png)

**Comment by Healix** [comment]
While an account is active, programs that were removed won't be removed until the account is exited. Alternatively, you had the program configured under "Settings > Guild Wars 2 > Launch options" (applies to all accounts) and "Edit > Launch options" (applies only to the 1 account).

What happens if you click notepad (under Run...)? It should cause it to start. 

If it starts, right click any account > Selected > Disable run after. If it's now checked, click it again to uncheck it.

If it didn't start, I'd guess Windows (or other security software) is blocking Gw2Launcher from starting programs, though that should also block it from launching GW2. Right click Gw2Launcher.exe, select Properties and there should be an option to unblock it if it's blocked.

**Comment by Healix** [comment]
If clicking (under Run..) doesn't start it, try the [beta version](https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe). It'll show an error message if the program fails to start for whatever reason.

**Comment by mrmodius** [comment]
I had it set to apply to all accounts, not just one specific account just as you said. Following those instructions got it to work again though, thank you :)
