### ISSUE TITLE
Darken /Hide initial window 

### ISSUE THREAD

**Issue by barbarolucente** [Healix/Gw2Launcher#251]
Hi, I was using the old 6704 build and just updated to 7075 and:
-Darken initial window works but like 1-2 seconds later so it still shows the white window before, then it turns black
-Hide initial window doesn't change anything, either alone or paired with Darken option, and sometimes makes gw2launcher crash

I'm using Windows 10 v1803

Thanks for your work!

**Comment by Healix** [comment]
The option to darken the window basically isn't useful anymore. Originally GW2 had a white background before showing character select, but they made it black with DX11. In one of the DX11 updates last year, GW2 started freezing while initializing, which causes it to get stuck with a white window, which should normally only be a flash. If Gw2Launcher happens to darken it first, then it'll be black, otherwise a frozen window cannot be modified, so the option to darken it will do nothing, then when it unfreezes, GW2 itself makes it black. You may be able to improve it by prioritizing GW2 (Settings > Guild Wars 2 > Process priority while initializing: high); the beta version had this enabled by default.

The option to hide the window should make GW2's window invisible after clicking play. This can still fail however if it's too slow, which may cause the window to go invisible seconds later (it has a 5 second limit). You may be able to improve it by prioritizing Gw2Launcher (Settings > General > Process priority: above normal or higher). This method gets around the freezing problem by having Gw2Launcher "own" GW2's window, but this has the side effect of both processes being affected, so if GW2 throws an error, Gw2Launcher crashes (but I can fix that).

**Comment by barbarolucente** [comment]
Ok, I didn't think it was GW2's fault because with the build I was using it's working fine as always (no white blink, both DX9 and DX11)
Haven't checked the release with a DX11 account tho, i'll try.
Thanks for reply.

**Comment by Healix** [comment]
I tested DX9 to be sure. Unlike 11, 9 is still using a white background, so it might not simply be freezing. If you're using the option to launch behind other accounts, that will prevent it from making it black, however that would have also applied to the old version.

I looked through the old version just to be sure and there was only 1 difference - it applied twice - so I added that and a fix for the launch behind option to the [beta version](https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe). Note if you have the option to hide the window enabled, the option to darken it is ignored.

**Comment by barbarolucente** [comment]
I tried the beta launcher and here's what happens:

-DX9 +launch behind with just darken window: white for 1 second, GW2Launcher freezes untill the game gets into character selection;
-DX9 +launch behind with hide+darken: white for 1 second then black , GW2Launcher freezes untill it can hide the window like 1 second before to get into char selection;
-DX9 -launch behind: darken works fine, hide works just a second before char selection, no freeze at all;

-DX11 +launch behind does same as DX9: white blink, no hide, GW2Launcher freezes;
-DX11 -lauch behind does same as DX9: darken works fine, hide works just a second before char selection, no freeze at all.

Resume: launch behind with DX11 and DX9 makes gw2launcher freeze, white blink before dark. Hide works just 1 second before char selection.

With the old beta i was using, launch behind is on, but no freeze and now white blink with both DX11 and DX9.
Hope it helps.

**Comment by Healix** [comment]
Are you sure it's freezing, rather than GW2 taking priority and basically making everything else freeze? It's likely to do that when you have GW2 set to a higher priority than Gw2Launcher, and in extreme cases, the entire system will freeze until GW2 loads character select.

The darken/hidden option is extremely time sensitive, as it needs to slip in within milliseconds of GW2 creating its window, just prior to initializing DX, which is where it freezes and I can no longer do anything to it. The current and old beta versions are functionally identical if the same options are used, it's just anything that slows it down is going to make it not work.

I did find a few bugs, but they were unlikely to be encountered. If you enabled, then disabled the account bar for example, it would break it until Gw2Launcher was restarted. I also fixed a memory leak and overflow with the hidden option, which may have been the cause of the crash.

The [beta version](https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe) is now 7079 (verify the build under Settings > Updates; some people have had a problem with downloading a cached copy).

**Comment by barbarolucente** [comment]
With the new beta darken is working fine, hide still doesn't work from the start (the window still pop and shows pretty much for all its duration) but that's not a problem since i just want it to be black.

Thanks very much for your work!
