### ISSUE TITLE
Launcher close gw2 after put in account name and password

### ISSUE THREAD

**Issue by jor8888** [Healix/Gw2Launcher#255]
with new beta version I have encounter this problem every 10 + accounts launch : Launcher close gw2 after put in account name and password  I tried changing the tweak timer from 0 to 5 sec on both setting still doing it.

**Comment by Healix** [comment]
Does it close immediately after entering the email/password, or is the login button clicked (GW2 tries to login)? 

Is it just closing GW2, or is it re-launching that account? If you have the timeout set for automatic logins (Settings > General > Launching), it'll re-launch the account when GW2 shows a connection/login error.

Does the status of the account show it as failed (instead of when it was last used)? Hovering over a failed status will give a reason.

If you're using the option to hide the initial window (Settings > General > Windows), try disabling it. This _could_ cause GW2 to close at any point between when it enters the login to when character select is loaded.

The beta version is currently the release version with minor changes mainly related to the hidden window option. I'm assuming if you try the current release version, it'll have the same problem.

**Comment by jor8888** [comment]
its on automatic put in account name and password, it show not log on for that day and went to next one did not relaunch since I dont have timeout set. Darken the window is not checked.  Maybe I will change the relaunch setting, thx.

**Comment by Healix** [comment]
Are you actually watching it close after entering the login, or are you assuming it didn't launch based on the login indicator?

I looked through everything and there isn't anything that could close GW2 at this point that didn't require interaction or to be specifically configured (like a hotkey or a "run after" program to kill GW2). The most likely accidental closure would be holding the left mouse button down on an active account.

For potential bugs that could close it, it would only be the "hide the initial window" option, which could cause GW2 to silently crash. The automatic email/password entry _could_ potentially cause GW2 to close under heavy load, but it would also cause the password to not be entered and would only be possible if the option "verify the login has been entered" (enabled by default) under tweaks was disabled.

If you're only assuming it didn't launch based on the login indicator, note the new version requires loading a character and could take several seconds to trigger when running multiple accounts sharing the same mumble link name. To disable this, uncheck Settings > Tweaks > Use MumbleLink to track daily login, or to make it more accurate, enable Settings > Guild Wars 2 > Launch options > Mumble link name.

**Comment by jor8888** [comment]
under further observation it close the client by itself after loaded into the zone I wonder if its dx11 crashing.  I dont have this problem with old version I am using atm which is 12-22-2020 version only problem I have with this version now is the daily logon chest doesnt disappear with dx11.

**Comment by jor8888** [comment]
anyway to get the order version to test it out?  the September 24, 2021, Build 6511 | release 16 build?  thx

**Comment by Healix** [comment]
6511 (September 24, 2021):
https://github.com/Healix/Gw2Launcher/raw/9a2031dd5b0f420e3a9764c5ad7aa31f349e7909/Gw2Launcher/bin64/Release/Gw2Launcher.exe

The previous beta version (November 18, 2022):
https://github.com/Healix/Gw2Launcher/raw/f721c8d0dec8c420f8edbb74446c26799103ff1d/Gw2Launcher/bin64/Beta/Gw2Launcher.exe
