### ISSUE TITLE
Temp folder really huge

### ISSUE THREAD

**Issue by FallenGrove** [Healix/Gw2Launcher#26]
Haven't had any issues with this before, but I noticed my hard drive was filling up unusually fast. Ran windirstat and it showed that the temp folder was 135 gb.

**Comment by Healix** [comment]
I'm assuming it's caused by gw2cache folders? This is somewhat of a flaw in the way GW2 handles the folders.

To fix this:

Right-click any account > Settings > Tools > Local.dat. Enable the use of static cache folders.

Alternatively, you can have Gw2Launcher automatically delete old cache folders by right-clicking any account > Tools > Delete cache folders.

**Comment by FallenGrove** [comment]
Actually this wasn't found in the gw2cache folders, but within Gw2Launcher\data\temp. I made a bat file that clears the folder every day, but I didn't know that gw2launcher had that capability. Thanks for letting me know!

**Comment by Healix** [comment]
That is where the gw2cache folders are located when using Gw2Launcher. The files should have been automatically deleted after 7 days, but there was a bug preventing that. The new build fixes that.
