### ISSUE TITLE
Arcdps stopped working since last update(months ago)

### ISSUE THREAD

**Issue by ChoriSw** [Healix/Gw2Launcher#266]
Heya, as title suggests, my arcdps stopped working all of a sudden. Tried replacing it on the main folder which is this: "C:\Games\Guild Wars 2\Guild Wars 2\bin64" but nothing changed.

Anyone knows what the steps are to check if i may have fucked up something and i dont know it? kinda newbie here

**Comment by Healix** [comment]
The bin64 folder is for DX9. For DX11, place [d3d11.dll](https://www.deltaconnected.com/arcdps/x64/d3d11.dll) in the main Guild Wars 2 folder.

Note they've been forcing DX11 recently, since DX9 will be removed in April, so if it stopped working one day, chances are this is why. If you want to force DX9, add -dx9 to the launch arguments.

**Comment by ChoriSw** [comment]
> The bin64 folder is for DX9. For DX11, place [d3d11.dll](https://www.deltaconnected.com/arcdps/x64/d3d11.dll) in the main Guild Wars 2 folder.
> 
> Note they've been forcing DX11 recently, since DX9 will be removed in April, so if it stopped working one day, chances are this is why. If you want to force DX9, add -dx9 to the launch arguments.

Main folder you mean this? "C:\Games\Guild Wars 2\Guild Wars 2" ,placed it there but nothing changed. Also, tried to force dx9 and worked perfectly fine. how do i fix the dx11 issue though? Am i placing it in the wrong path?

**Comment by ChoriSw** [comment]
Nvm, it worked with both now, had to force -dx11 though after placing it in the main folder next to "gw-64.exe"
