### ISSUE TITLE
Feature Suggestion: Jumplists

### ISSUE THREAD

**Issue by xvwyh** [Healix/Gw2Launcher#28]
Gw2Launcher already allows for creation of shortcuts to automatically launch each account without opening its UI. The shortcuts can be pinned to taskbar or to start menu, sure, but each takes up valuable space, and the more accounts there are - the most space they consume. A random idea came into my head that Gw2Launcher could also support jumplists for the same purpose of launching accounts while bypassing the UI, where each jumplist item will represent a saved account:
![image](https://docs.microsoft.com/ru-ru/dotnet/media/wpfshell-jumplist.png)
That way, users can just pin the launcher to taskbar/start menu, right click it and pick the desired account.

Jumplist "task" items aren't much different from shortcuts, so the exact same `-l:silent -l:uid:...` command-line arguments can be used. And seeing that Gw2Launcher is coded in C# - adding support for them should be a fairly trivial task.

**Comment by Healix** [comment]
I've added support for it to the [beta (64-bit)](https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe) version. If you have recently opened items enabled, it'll support pinning and removing accounts, otherwise it's limited to a fixed list.

For something similar, I've also added a new feature to show the "account bar" in a popup format by using "Gw2Launcher.exe -quicklaunch".

**Comment by xvwyh** [comment]
Looking good, thank you. Although it doesn't seem like `-l:silent` argument is working properly, because it keeps opening the main window not in minimized state (as the code suggests it should), regardless of whether it's from a shortcut or from jumplist.

**Comment by Healix** [comment]
[Updated](https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe). Alternatively, enable settings > general > show tray icon + minimize to tray, then it will hide in the tray when starting silently.

**Comment by xvwyh** [comment]
Perfect. Thank you.
