### ISSUE TITLE
Mutex killer doesn't work in linux (wine)

### ISSUE THREAD

**Issue by SophiaHadash** [Healix/Gw2Launcher#29]
While running the launcher in linux, everything seems to work except for the mutex killer, preventing the launcher from running multiple clients. Although I presume you don't support the launcher for linux, it might be interesting for you given that everything else already seems to work very well.

**Comment by Healix** [comment]
I looked into it and the necessary function isn't implemented in Wine. Fortunately, an older function from Windows 9x was available, but only partially with missing data. I was able to workaround this, but if I were to try this on Windows, it would hang.

Assuming 64-bit, try:
https://github.com/Healix/Gw2Launcher/tree/master/Gw2Launcher/bin64/Beta
(tested on Ubuntu, Wine 5 + .NET 4.5)

**Comment by SophiaHadash** [comment]
Thank you for the quick response! I've tested it with my environment (which is this pre-installed version from https://github.com/liberodark/GW2-Wine) (64bit, Wine 4.0-rc2, ubuntu 20.04 LTS, .NET 4.0) and it is still not working. Do you think I should try upgrading .NET or wine?

**Comment by Healix** [comment]
Oddly, this older version of Wine supports the newer Windows function, but still only partially. The fix I previously added only applied to the older function, so it didn't apply to this version of Wine.

I've updated the beta to support both:
https://github.com/Healix/Gw2Launcher/tree/master/Gw2Launcher/bin64/Beta

As for using .NET 4.0, are you sure? Only having 4.0 should cause an immediate crash, since Gw2Launcher requires features from 4.5. If you have Mono, which Wine may have installed by default, it would be using that instead, which has other problems - launched accounts will get stuck with the status "launching", which will prevent other accounts from starting until the previous closes.
