### ISSUE TITLE
bug: TOTP code does not enter with CeF (using auto-fill option)

### ISSUE THREAD

**Issue by wharlox** [Healix/Gw2Launcher#295]
build 7084

after logging in, the next field is the auth and cursor in the input box already; but does not submit the totp code.

the workaround is to `-usecoherentui`

**Comment by Healix** [comment]
This feature will be exclusive to CoherentUI for a while. CoherentUI provided a real time log that let me see everything the launcher was doing, so I knew exactly when the login succeeded, failed, or the code was required. CEF doesn't have that.

**Comment by KTkabo0m** [comment]
Will there be a patch? I noticed since the update on Tuesday that the auto-fill info no longer goes in . From what I gather from all the technical stuff you have said, this is what you are talking about so that is why I commented in here as the topic is the same.

**Comment by wharlox** [comment]
oh interesting and oof wait a pain with the change then!

so, if my understanding is right from what i just dug into; is it along the lines of: coherentui published an event via coui and it was easy to read - and now with cef it's using a different framework - and now it is a matter of being able to read that new information (if at all)?

**Comment by Healix** [comment]
> Will there be a patch? I noticed since the update on Tuesday that the auto-fill info no longer goes in.

The TOTP code? There's won't be a fix for CEF for a while. Use the -usecoherent option to keep using CoherentUI.

The email/password? Use the [beta version](https://github.com/Healix/Gw2Launcher/blob/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe?raw=true).

**Comment by cpboyd** [comment]
@Healix Is there a branch with the beta version changes in case you want help with the TOTP code stuff?

**Comment by Healix** [comment]
I already have a way to do it, but I'm currently prioritizing the next release, which should be within a few days.

Entering the code for CEF will never be as nice as CoherentUI. I can actually do something similar for CEF, but I don't consider it viable since it requires admin privileges and would certainly be flagged as a virus. I found a way to detect when CEF is either logged in or requires the code (they both have the same trigger), so I'm just going to go with the simplest solution of assuming the code is always required and entering it a second after clicking play.
