### ISSUE TITLE
Build 7089 pasting existing clipboard contents

### ISSUE THREAD

**Issue by turbodog** [Healix/Gw2Launcher#306]
For me build 7089 is pasting in the existing text from the clipboard rather than account email address. I tried with 7084 and it pastes email as expected. With 7089, launching in normal mode didn't make a difference. 

Further note: if current clipboard contains "foo" then I see "foofoo" being pasted in the email field repeatedly.

**Comment by Healix** [comment]
The current version ensures that GW2 is the one accepting the clipboard. If something else intercepts it first, it'll redo the clipboard and try pasting up to 3 times. During these resets it's possible for GW2 to paste what was previously on the clipboard. You can check the log (right click any account > Tools > Log) to confirm if it's being intercepted and by what process.

If you have something monitoring the clipboard that is always going to intercept it, there's nothing I can do. I can remove the check and go back to assuming it was pasted, which will work, but that kind of defeats the purpose of using the clipboard, so you should use post or send instead (Settings > Guild Wars 2 > Tweaks > Change how the email/password is entered). That said, if you plan on using the automatic authenticator entry for CEF, it requires using the clipboard, since there's no other way of knowing if the code is actually needed, so if I removed the check, it could potentially click a link instead of the submit button when it's not needed.

**Comment by turbodog** [comment]
Wow thanks @Healix and the logs had the answer. Something from WSL was stealing focus and disabling that seems to have resolved the issue.
