### ISSUE TITLE
Addons not Loading for alt Acc

### ISSUE THREAD

**Issue by Taladorn** [Healix/Gw2Launcher#316]
I noticed with the recent Update, only the first account to launch gets AddOns like ArcDPS/BlishHUD Loaded correctly.

**Comment by MasterOfTheRealm** [comment]
Same for me, I tried everything, even messed with all the possible localization options, the addons work on the account that was launched first no matter which one it was and any proceeding multibox accounts have no addons loaded whatsoever. Worked fine for all accounts simultaneously before the update yesterday.

**Comment by Taladorn** [comment]
[gw2al_log.txt](https://github.com/Healix/Gw2Launcher/files/11554009/gw2al_log.txt)

Thats the Log from the addonLoader for the account that doesnt work if that helps

**Comment by Healix** [comment]
The patch changed CEF so it's no longer shared between multiple clients. This causes the location of the bin64 folder to change when one account is already using it. If you're using the addon manager, which loads files out of bin64, it won't work because of this, whereas arc as d3d11.dll in the base folder will. It's unfortunate they did this, because CEF is ~300 MB per account and it seemed to work fine while shared.

CoherentUI is still shared, so you could just add -usecoherent to the arguments under Settings > Guild Wars 2 > Launch options.

Localized execution set to binaries should work for CEF. If you want to set it to full, you'll need to manually copy the bin64 folder to each account's Gw2Launcher\\# folder.

**Comment by Taladorn** [comment]
So either -usecoherent which will most likely get removed at some point or the localized execution.
What's the difference between localized and default settings tho?

And thank you for your fast response (:

**Comment by Taladorn** [comment]
if I read that right, I am already using the settings you have described?
Localized with Full

![grafik](https://github.com/Healix/Gw2Launcher/assets/52274600/58297ddf-adbb-4cd1-83b6-e74d2488dc6e)

**Comment by Healix** [comment]
Localized execution set to full will by default share CEF with other accounts. This is why you have to delete the bin64 folders located under the Gw2Launcher folder, then copy the original bin64 folder to each Gw2Launcher\\# folder.

If you want the same addons on all accounts, changing it to binaries is the simpler option. This option generally isn't useful anymore, except in this instance since the addon manager still uses the bin64 folder.

**Comment by Taladorn** [comment]
I am in fact using the AddonManager.

If I end up copying the bin64 folder, I guess I have to repeat that step on every update eventually?

Copying worked for me so I guess this Ticket can get closed.

Thank you!
