### ISSUE TITLE
CefHost.exe System error

### ISSUE THREAD

**Issue by absolutevibe** [Healix/Gw2Launcher#320]
Hello,
Ever since the most recent update, I started getting a system error below when I launch more than one session of GW2.

```
CefHost.exe - System Error
The code execution cannot proceed because libcef.dll was not found. Reinstalling the program may fix this problem
```

I can click **OK** to close the error and it will allow me to continue with multiple sessions. the only thing that seems to not work on the 2nd session is TP. Is there anything I can do to get rid of this error? I'm using the build 7195 (64 bit).

Thank you.
![cef](https://github.com/Healix/Gw2Launcher/assets/134744254/ce1e77f0-c857-4992-9e51-c6e030f680de)

**Comment by Healix** [comment]
Are you out of space? The file libcef.dll is created by GW2 on launch, so unless you're out of space or have security software deleting it, it should always exist.

The problem caused by the patch is now only 1 client can use CefHost at a time, which causes GW2 to create a copy of it in a temporary location every time you launch another account.

Settings > Guild Wars 2 > Management. Enable localized execution, set to binaries. This will create a Gw2Launcher folder where GW2 is located and CefHost will be kept in there, rather than a temporary location.

**Comment by absolutevibe** [comment]
I just checked and I have plenty of space on my HD. 
I followed your instruction and looks like that's how I have my launcher configured.
I checked the main GW2 directory and there is libcef.dll in E:\Games\Guild Wars 2\bin64\cef. 
I checked all profiles folder under the GW2Launcher folder and they all have libcef.dll in the same directory. Do you have any other suggestion on what I should do/check?

![dir](https://github.com/Healix/Gw2Launcher/assets/134744254/1d740e59-2e7b-424a-8207-a64c4d2e142c)
![settings](https://github.com/Healix/Gw2Launcher/assets/134744254/910453e9-1037-4a58-be64-0d39efcfe273)

**Comment by absolutevibe** [comment]
I just figured it out. It's my AV. I temporarily turned it off and no error when I launched the 2nd GW2 session. I'll figure out what I need to exclude, since the whole GW2 folder is already excluded. I appreciate your help. Thank you.
