### ISSUE TITLE
Launching arc only on selected accounts

### ISSUE THREAD

**Issue by manaflare94** [Healix/Gw2Launcher#325]
Is there a way to make arcdps (and addons I have for it) to launch only on selected accounts I want but not on all the other ones?
I am not quite sure how Virtual/Basic mode affect anything and how localized execution works.
Should I localize accounts I want arcdps to work with or ones I dont? or all of them? none? does it even matter?
Would manually deleting files of arc from \Gw2Launcher\%accname% work? Or what Should I do?

And if its actually possible to make arc work only on selected accounts out of all, how do I update/delete it if its broken with a patch later?

thx in advance for the answer

**Comment by Healix** [comment]
Enable localized execution, exclude addons, desired level full and synchronizing core. If you want arc disabled by default, choose to exclude accounts you want arc on, otherwise only include accounts you don't want arc on. You can update arc as you normally would.

Accounts using localized execution will have a Gw2Launcher\\# folder created on launch in GW2's folder. Note these # folders will appear to be copies of GW2's folder, but they don't actually take up space.

If you wanted arc on only 1 account, you would do the opposite and only have that 1 account use localized execution. You would then place arc in the account's # folder rather than GW2's folder. You could also do it this way if you only wanted arc on a few accounts, but each account would need to be updated when arc changes.

**Comment by manaflare94** [comment]
Thx, seems I had right idea at the start, just didn't delete arc from main gw2 folder, everything works now how I want it to!
