### ISSUE TITLE
Location of login reward status information

### ISSUE THREAD

**Issue by M6D6M6A** [Healix/Gw2Launcher#326]
I am currently having difficulty locating the specific location of the login reward status for individual accounts in the GW2 Launcher. This issue occurs when trying to determine which accounts I've already logged into for the day and received the daily login reward.

I understand that the GW2Launcher settings are stored in %appdata%\Gw2Launcher\settings.dat. However, I cannot confirm if the status data for the daily login rewards is also stored here.

Can anyone provide any guidance or clarification on the exact location of this data?

**Comment by M6D6M6A** [comment]
I just read that the Login Reward is triggered immediately after the login screen, is there a minimum recommended waiting time, or is it finished immediately after the loading screen starts, so I could press Alt + F4 to exit the window after, say, 1 second and still get the Login Reward? Will the saved data be updated so that the daily login icon will disappear, or will it remain in place?

**Comment by Healix** [comment]
All settings are in settings.dat. It's written on a delay and where exactly the data is located within the file is going to vary and change.

The login rewards trigger as soon as you connect to the server, which is generally as soon as you see the loading screen. Very rarely the server is delayed, which I'm not sure if it still counts (-maploadinfo will show it's waiting for the server prior to loading). If you want to be safe, watch for -maploadinfo to show it's actually loading, or if you want to be extra safe, watch for the map completion status to show.

If you alt+f4 on the loading screen, the daily login won't be tracked by Gw2Launcher, since it triggers when a character is loaded by default. Settings > Guild Wars 2 > Tweaks > Disable using mumble link for the daily login, then it'll trigger on character select instead.

As for trying to read the daily login data, what are you wanting to do? The simplest option is configuring a program to run after loading, then using that to track it. If you just want to track the date for example, you could have a script (echo.>"c:\\example\\%accountid%.txt") write to a file after loading a character, then you could simply check when the file was last modified.

**Comment by M6D6M6A** [comment]
Ty, for the quick reply, but I allready have code to close the batch (max loaded accounts) when the map is fully loaded. This should ensure that the daily login icon goes away and I dont have to track the logins elsewhere.
