### ISSUE TITLE
Dont let the GW2 launcher be on top of active windows.

### ISSUE THREAD

**Issue by pro0digy** [Healix/Gw2Launcher#34]
I have set up 20 account windows in tiles to fill the whole screen. The accounts are launched one by one after the character selection is loaded. When I try to interact with the already active windows, the GW2 launcher window constantly pops up and interferes. Is it possible that the windows in which the character selection is loaded are always higher than the GW2 launcher? Maybe add the always-on-top property to windows only after loading the character selection?

**Comment by Healix** [comment]
I'm assuming you're not wanting queued launches to pop up and interfere while they're being started? That happens because GW2 forces itself to the front when it starts, and Windows allows it because it's related to the currently active window. The top most setting shouldn't be a factor and is already only applied after loading character select.

The most I could do is push the launcher to the background after it pops up, then re-focus your last window.

**Comment by pro0digy** [comment]
Yes, that would do. Thanks.

**Comment by Healix** [comment]
You'll find this option under settings > general > launching in the latest version.
