### ISSUE TITLE
Some accounts getting SMS dialog when attempting to sign in, blocking auto-signin

### ISSUE THREAD

**Issue by jbran** [Healix/Gw2Launcher#340]
Only noticed this after the most recent patches in mid-July, and only on some of my accounts. The SMS dialog waits for input and prevents launcher from logging in for that account.

Not sure if this is patch related, something specific with these accounts, or if there is an option in the launcher to handle this (didn't see one when looking).

**Comment by Healix** [comment]
2FA is required whenever your IP doesn't match one of the IP ranges remembered by your account. If only some are triggering it, it's because they have different ranges remembered.

It's not possible to handle that for you, you have to enter the code and choose to remember it. If you were using an authenticator instead of SMS, then it could be automatic (it's under the security settings of the account).

**Comment by jbran** [comment]
Can confirm. Since that initial post-patch day, this has not recurred.
