### ISSUE TITLE
Frequently getting disconnected shortly after connecting to a VPN [ONLY Gw2]

### ISSUE THREAD

**Issue by Alex1016182** [Healix/Gw2Launcher#353]
This isn't exactly an issue directly with GW2 launcher directly, but I feel there might be an indirect link. Soon after the release of SotO, I have realised that when launching my alts (usually launch 10 at a time with a VPN for each group), but recently at pretty frequent intervals, they all simultaneously get disconnected with the error 7:11:3:202:101 which from a little googling doesn't seem to be anything special other than I lost connection to the GW 2 server. However, my internet connection remains intact. Any idea what could be causing this? I have tried to reduce the amount of alts that get launched at the same time but that doesn't seem to have helped. 

Initially, I was under the impression that I can no longer log in to GW 2 with this, but after waiting a little, new launchers do connect again

**Comment by Healix** [comment]
This is probably just internet problems. Somewhere along the route you're taking to reach GW2 is a problem. Your connection may be fine, but practically everything is taking different routes. If this is the case, your only option is to wait it out or attempt to get on a different route by trying various VPN servers, which may or may not be possible depending on where the problem is and what's available.

**Comment by Alex1016182** [comment]
I think you're right, I did a more intensive test and tried to catch it as it was happening and my connection had definitely slowed at the same time, numerous times. It must be an issue with my VPN. Thank you!
