### ISSUE TITLE
Not really an issue, just a question about multi blish hud

### ISSUE THREAD

**Issue by svefn** [Healix/Gw2Launcher#362]
Hi, 

So I got Blish to run on all accounts by using the MumbleLink and adding Blish in global settings, they all share the same Blish settings as I wanted and is working fine. 

But I just want Blish to run on my main account some times, so I right click these alt accounts and select 'Disable run after', but it also disables run after on my main account. 

How do I make it stay ticked for only some accounts? shouldn't the Selected menu option be selective and not apply to all accounts?

**Comment by Healix** [comment]
The disable run after and disable automatic logins is really only there for convenience, since it's possible to directly open the selected menu by right click dragging. You'll notice if you check it, it'll also be checked under the all menu.

That said, I could easily make disable run after only apply to selected accounts. I've changed it in the [beta version](https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe) if you want that now. 

Alternatively, if you're always launching the same accounts, you can create a shortcut to launch the accounts and add the option -l:disablera to the shortcut, which will disable run after only for that launch.

**Comment by svefn** [comment]
Thanks, I think applying to selected sounds best because that was what I expected when the menu item is for selected. For now I've removed the MumbeLink for other accounts so they don't start Blish which also works.
