### ISSUE TITLE
"I am Evon Gnashblade" setting not surviving relaunch

### ISSUE THREAD

**Issue by I3igAl** [Healix/Gw2Launcher#366]
For information, if you type "I am Evon Gnashblade" into the Trading Post search window, the Trading Post UI changes to be more compact. Doing this without GW2Launcher (launching game directly from main .exe) will survive exiting game. I cannot get it to stay for my muiltibox accounts. Even if I right click -> Selected -> Launch (normal) and then enter the Evon phrase, then close the game, it will not stay either when launched normal or multibox the next time.

I had this issue with having my volume settings revert over and over, and launching as normal to set them once per account fixed it, but it does not fix Evon. I can launch directly from the root exe, have it function, and not function immediately after on the same account using GW2Launcher.

Please advie. 
![image](https://github.com/Healix/Gw2Launcher/assets/80173503/9a6b3156-0f0d-4804-95db-0d43a9b8aa6e)
![image](https://github.com/Healix/Gw2Launcher/assets/80173503/064d85dc-cfaa-46af-af76-918c532fb172)

**Comment by I3igAl** [comment]
Just to update, I got frustrated and went nuclear, started over from scratch with GW2Launcher. went through the initial setup, first time launch I told it to start in normal mode,  adjusted my settings as desired for the new Local.dat file. This included all settings through F11 menu, and typing "I am Evon Gnashblade" into the TP. I hit F12, logged out, the launcher popped up and auto logged in again, every setting from F11 saved but Evon did not save.

However once I close down the GW2Launcher launched accounts, and GW2Launcher itself, then manually launch and log in from the main install, Evon Gnashblade IS saved. Either GW2Launcher is not saving this to Local.dat for the separate clients, or its preserved in some other location that GW2Launcher is not grabbing, or deleting after logout.

**Comment by I3igAl** [comment]
Did another couple of clean fresh starts. every time I made sure Evon was turned on in the main install. I meticulously went through the options in GW2Launcher, trying different setups (shared local.dat, copied local.dat, new local, localized exec on and off, binary or full) and could not get it to stick. I give up because I just want to play the game and its not worth the headache any further.

**Comment by Healix** [comment]
This setting isn't stored in Local.dat, it's in gw2cache. Normally this setting would only be reset with patches when they clear the cache, but in the case of Gw2Launcher, it's reset on every launch because it also happens to be where they store the login reminders.

If you want to get this to save, there's a few requirements. 
1. You'll need a static cache location, which you can enable under Settings > Tools > Local.dat. Alternatively, you'll have to use Launch (normal) after every patch for GW2 to remember the location itself.
2. Using an authenticator or SMS will be required to disable the login reminder. Right click the account > Edit > Security. Enter the authenticator key. If you're using SMS or don't want to enter it, enter AAAAAAAAAAAAAAAA
3. Use the [beta version](https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe), I've added a very simple change - it will not reset the cache when the account has an authenticator key.

Now it will save.

**Comment by I3igAl** [comment]
It is now working as I wanted, thank you for being awesome and a responsive developer. I didnt expect an answer or a solution so soon.

I had already done 1 on your list, 2 I skipped over because I do have SMS protect enabled, and 3 is well, either a new thing you did or just hidden on the repo because I cant see any beta releases. in any case im all set up now, thank you!
