### ISSUE TITLE
Updated launcher deleted all my account profiles

### ISSUE THREAD

**Issue by FallenGrove** [Healix/Gw2Launcher#38]
After updating to the newest version of the launcher today it found none of my alt accounts and only one account I added almost a year ago. I looked in the appdata/roaming/gw2launcher/data folder and it seems like all my account settings are there, but the launcher can't find them.

**Comment by Healix** [comment]
Open %appdata%/Gw2Launcher/. In this folder should be a backups folders. Copy the folder just to be safe.

Update to the latest version of Gw2Launcher.

Delete %appdata%/Gw2Launcher/settings.dat. Open the backups folder and delete any files that were created since the problem occurred. Launching Gw2Launcher will automatically use the first backup that is successfully loaded.

Problem was, it would fail to load the settings if a stored password couldn't be decrypted.

**Comment by FallenGrove** [comment]
It loaded one profile, but the rest was unable to be recovered. I guess the passwords can't be decrypted on those. Which I guess is fine since I made the profiles a long time ago. I'll just re-add the accounts and settings back.
