### ISSUE TITLE
Some accounts have input lag

### ISSUE THREAD

**Issue by Miss-Lana** [Healix/Gw2Launcher#383]
As title, some of my alt accounts have input lag. This doesn't affect all of them, only a handful. It happens regardless of what other programs are running, or whether I launch those particular accounts just by themselves or not. All my accounts use the same settings.

This has been happening for a while, but I haven't thought about looking into it until just recently, and am at a loss as to why some accounts are affected but others are completely fine.

**Comment by Healix** [comment]
Client or server lag? Is all input delayed, where you can watch the letters being typed in chat, or is it your skills blinking, showing that the key was pressed but it's having to wait for the server to respond?

If it's server lag, were some accounts registered to NA and others EU? You always connect through the region the account was originally registered to, though this should only impact authentication. You can check the account's region under account.arena.net. Try using port 80 or 443 (Edit > Launch options), which can change how GW2's traffic is handled.

If it's client lag, verify the graphics settings are the same. This type of lag would be caused by low system resources (high CPU usage, low memory, low GPU memory) or other software acting in the middle. Ensure the priority and affinity of one of the affected accounts isn't set to a low value (Edit > Launch options > Processor).

Is it always the same accounts? If so, disable automatic logins, and launch 2 accounts, 1 that's affected and 1 that isn't, then manually enter their logins into the other, so that the 1 that was affected is using the login of the 1 that isn't. Have them together in the same instance where they can see each other to confirm the problem is specific to the account.

**Comment by Miss-Lana** [comment]
It's client lag, not server lag. Dragging items is sluggish, moving and jumping is sluggish, etc, etc. Can be hard to do jps with it.

I'll check the settings again and test that stuff out, see if anything changes.

**Comment by Miss-Lana** [comment]
I managed to figure out it's the three accounts that I have set to launch as half of my screen. The windows are set to be 960x1080, and those three accounts are the only ones having an issue.

I cloned one of the accounts that didn't have the lag, and logged in with the credentials of an account that was having the lag. That fixed the problem. Just have to do it again and see about putting them back in order again.
