### ISSUE TITLE
Takes very long to set window size and position

### ISSUE THREAD

**Issue by dameischta** [Healix/Gw2Launcher#39]
Since the new version, Gw2Launcher needs a very long time to set the window size and position. About 30 seconds after the account/character is logged in.

Via "Right click -> Selected -> Apply Window Bounds" it works fine.

Strange thing is:
When I open the "Black Lion TRading company", the window size & position is assigned immediately.
... it seems to be somehow the fault of Guild Wars 2 itself?!?

**Comment by Healix** [comment]
GW2 did change how it loads within the last month or so, causing Gw2Launcher to rely on a backup method. Opening the trading post causes GW2 to start another process, which is one of the triggers Gw2Launcher watches for and why the window is set at that point. The older version is also affected, it's just less noticeable.

The backup method is one I didn't want to rely on since it may vary by OS, and it currently only applies if both Gw2Launcher and GW2 are either 64-bit or 32-bit. Assuming you're using 64-bit in both cases, try this beta version:

https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe

**Comment by dameischta** [comment]
Wow, that was a really fast fix :-)
-> With the beta version the assignment of window position & size works again.
