### ISSUE TITLE
Updating local.dat without progress

### ISSUE THREAD

**Issue by trashcandrummer** [Healix/Gw2Launcher#401]
I don't know what happened but for at least two GW2 patches the GW2Launcher notifies me to update my local.dat.
If I press "Yes" on if I want to update now, the launcher will open, download the first ~20MB and closes again, yet nothing more happens afterwards.
I only see this screen then:
![pic](https://github.com/Healix/Gw2Launcher/assets/48524287/12009dd3-ca37-4b0c-bf09-7087e8af6193)

This processed finished in the last couple of months without any problem.
I already tried deleting everthing but ```settings.dat``` in ```%appdata%\GW2Launcher\``` yet with no success on the update progress.
I am only able to launch my alts using ```Launch (normal)``` and even after a normal launch the launcher will ask again to update the local.dat.

Is there any cache I can delete or do I really need to remove all accounts and start from new?

**Comment by Healix** [comment]
GW2 currently has a problem on some systems where its process will remain running after GW2 visually exits. Updating gets stuck because of this.

When this happens, you'll have to kill GW2's process. To kill all instances of Gw2-64.exe, press WindowsKey+R and open:

taskkill /IM Gw2-64.exe /F

Alternatively open the task manager (ctrl+shift+esc), find GW2 under the details/processes tab, right click it and end task.

**Comment by trashcandrummer** [comment]
Thanks for the quick reply! I already killed all processes many times, so I just have to retry until it works at some point?

**Comment by trashcandrummer** [comment]
I tried it now a few more times and now it worked for some reason. Good to know this is not really a GW2Launcher issue. Thanks for the help!
