### ISSUE TITLE
Shortcut / Icon for "Start after" programs

### ISSUE THREAD

**Issue by Vathana-Git** [Healix/Gw2Launcher#407]
Hello,

Is there a way to show program shortcuts / icons on the launcher for programs I added via settings to start after I launch my accounts?

I set up Blish Hud under global settings with mumble links and set it to "Manual," so currently I have to Right Click -> Selected -> Run.. -> Blish to start, and I wonder if there's a quicker way I might have missed.

Thanks a lot!

**Comment by Healix** [comment]
No, there's no shortcut for it. Instead of right clicking to open the menu, hold the right button and move the cursor a bit (it'll show a selection box), then release to have it directly open the selected menu (older versions required selecting multiple accounts to do this). The only faster way would be setting the "Run..." popup to stay open.

**Comment by Vathana-Git** [comment]
Ah, okay thanks. Guess I have to resort to that or set up three hot keys to start Blish for my three accounts. Thank you!
