### ISSUE TITLE
can only start with Launch(normal)

### ISSUE THREAD

**Issue by eric-boone** [Healix/Gw2Launcher#413]
I can only start accounts with right clicking > selected > launch(normal).

On start up it tries to update accounts but times out.

No other gw2 process is running in the background.

**Comment by eric-boone** [comment]
I have checked it through the whole process. That setting is/was checked.

Just to be be thorough here are the steps I'm taking:
While watching the details tab of the task manager.
I do not see the Gw2-64.exe running.
I start Gw2Launcher and click yes to update on the pop up.
The updating progress bar window opens for Gw2Launcher.
Gw2-64.exe shows up in task manager when Gw2 has a download pop up window.
The progress bar window time out with a no changes warning.
I click abort.
The Gw2-64.exe process ends.
The progress bar window closes a few seconds later, no progress has been made.

**Comment by StephanWells** [comment]
Can confirm, same problem here.

**Comment by Healix** [comment]
> Gw2-64.exe shows up in task manager when Gw2 has a download pop up window. The progress bar window time out with a no changes warning. I click abort. The Gw2-64.exe process ends. The progress bar window closes a few seconds later, no progress has been made.

Aborting cancels the update. Right click Gw2-64.exe in the task manager and select end task, then it'll continue.

GW2 started having this problem after the patch in January. On Windows 11, GW2's process can remain running after GW2 visually exits, and since updating waits for the process to exit, it gets stuck. Most people with this problem have found it to be caused by arcdps, but a few have confirmed it happens regardless.

**Comment by eric-boone** [comment]
Great, Thanks! It is working again.

So just to clarify in case some one finds this in the future. I ended the Gw2 process in task manager when the updater gave the warning like in @StephanWells screen shot. the update process continued as normal after that.
