### ISSUE TITLE
Stuck updating Gw2.dat 

### ISSUE THREAD

**Issue by GeneratingShelf** [Healix/Gw2Launcher#417]
I'm having an issue where the launcher is trying to update Gw2 even after I have the most up to date patch installed through the Anet launcher. Everytime I try and launch the update window comes up and the bar gets to halfway and then stays like this for a couple of minutes before a warning message comes up saying there have been no changes for over a minute. I've tried completely deleting the app, clearing the appdata and redownloading but the same issue happens. Are there any steps I can try to fix this issue? 
![image](https://github.com/Healix/Gw2Launcher/assets/165337660/8a276664-7dcb-436c-9de1-8a44a5caec2e)

**Comment by Healix** [comment]
GW2 has a problem on Windows 11 where its process will remaining running in the background after GW2 visually closes. Gw2Launcher waits for GW2 to exit while updating, which is why it's stuck. When this happens, open the task manager (CTRL+SHIFT+ESC), find Gw2-64.exe under the list of processes, right click it and end task for the update to continue.
