### ISSUE TITLE
Running Multiple GW2Launcher Instances

### ISSUE THREAD

**Issue by SalvorinFex** [Healix/Gw2Launcher#418]
Greetings Guiulders,

Is there any way to run Multiple Instances of this Launcher?
I had used the BETA version as this option, but it appears to not be available anymore.

My reason for this is to be able to run GW2 from other installed locations, mainly for testing.

**Comment by Healix** [comment]
The "beta" version isn't really a beta version, it's almost always for testing something for someone. The ability to launch multiple instances was only briefly available for someone who had a broken OS that was preventing Gw2Launcher from starting because of it.

I've added 2 command line options to the [beta version](https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe).

- -multi will ignore if there's an existing instance of Gw2Launcher (fun fact, GW2 originally had this option)
- -readonly will prevent Gw2Launcher from saving its settings, since generally the last one used is going to save

**Comment by SalvorinFex** [comment]
You ROX Healix, True Dev Hero!

**Comment by SalvorinFex** [comment]
Hey Healix, Just tried the `multi` in the Properties as well as the Launcher Location command line, but it's still showing my existing launcher accounts.  Where I am going wrong with this?

**Comment by Healix** [comment]
The settings are stored in a single location, so every instance is going to have the same settings. The old beta version would have had this same problem.

I've added another option to the [beta version](https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe). You can change where the settings are stored with the -appdata option. The default would be:

-appdata "%appdata%\Gw2Launcher"

If you want the settings stored in the same folder as Gw2Launcher.exe, you can simply put:

-appdata "Gw2Launcher"

Note both instances are going to detect an account as active if the accounts have the same ID, so either copy the settings from the first, or create/clone accounts until the new accounts you want to add have unique IDs. Alternatively, since you have 2 installs, you can simply rename Gw2-64.exe for the second one, since it's based on the file name.
