### ISSUE TITLE
CPU usage per client suddenly up 3-4x?

### ISSUE THREAD

**Issue by raikoo** [Healix/Gw2Launcher#430]
Last week I could reasonably run 20 accounts simultaneously, and have done so for a few months, since the game seems to have a deep sleep or low resource mode (on average my clients were using ~1% CPU usage each) but seemingly overnight that has gone up to ~4-5% CPU usage per client and has become too much, is there a setting or something I can do to fix that?

**Comment by Healix** [comment]
Ensure your graphics settings didn't change, especially the frame limiter.

If nothing changed, chances are it's due to a Windows update, security software, or you need to reboot.

Other than that, you can only de-prioritize background accounts to lessen their impact on everything else. To do this, select the accounts, right click > Edit (multiple) > Launch options > Processor. Set the priority to low, and if you want to go even further, limit which processors they can use.

**Comment by raikoo** [comment]
I made some adjustments taking your advice, I did a pass on my graphics settings (the frame limiter was off! I had thought I had it on) and changed the process prioritization, fixed my issue and runs better than before I had the problem! Thank you for your help.
