### ISSUE TITLE
unable to move windows mode with sizer program have to mannually drag the window 

### ISSUE THREAD

**Issue by jor8888** [Healix/Gw2Launcher#44]
unable to move the window with the sizer program have to mannually drag the window even tho the Prevent resizing/moving the window is unchecked.

**Comment by Healix** [comment]
Do you mean the window position you've configured isn't being automatically applied after launching the game, or you can't move the window while using the positioning tool?

If the window position isn't being automatically applied, that should be fixed in the beta version:
https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe

**Comment by jor8888** [comment]
can't move the window while using the positioning tool, When I use the sizer position tool it goes to the position I wanted then snap back to original position from the launcher setting,  I have to drag it a liittle then I can use the program to position to where I wanted, it wasnt like this from the older version.  thx.

**Comment by jor8888** [comment]
upon furthur testing it looks like I have to wait 30 seconds before I can use the position program to move it, its weird.

**Comment by Healix** [comment]
When you're using the windowed option in Gw2Launcher, it will fight to re-apply your configured settings for up to 30 seconds and will stop trying if the window is manually moved. I had removed this in the previous build, but found it was a problem on slow systems and reverted it. How this works will continue to change as I test it.

It sounds like you're using another program to position GW2's window rather than the built-in tool - what's your goal? If you're just wanting to launch GW2 in windowed mode, note it'll do so by itself and can be changed within the game's graphics options.

I've updated the beta, lowering it to 1 second and you can now leave the window size/position empty if you only want access to the other options.
https://github.com/Healix/Gw2Launcher/raw/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe

**Comment by jor8888** [comment]
thx working good now.
