### ISSUE TITLE
Disable options for Selected accounts applies to all accounts

### ISSUE THREAD

**Issue by crackerbear** [Healix/Gw2Launcher#451]
I have 4 accounts, if I right click on 1 account and choose `Selected > Disable automatic logins` or `Disable run after`, the options apply to all accounts, as if I'd chosen the same setting but through `All` context menu option.

I'm trying to utilise the auto character select script from issue #369 but exclude 1 of my accounts by using using `Disable run after` on that selected account, but the setting is applying to all accounts.

**Comment by Healix** [comment]
Use the [beta version](https://github.com/Healix/Gw2Launcher/raw/refs/heads/master/Gw2Launcher/bin64/Beta/Gw2Launcher.exe) for "disable run after" to work per account.

These options were only under the selected menu for convenience, since you can shortcut to the selected menu via right click drag. Someone else requested "disable run after" to be per account a while ago, which is in the beta version. I could also make "disable automatic logins" per account, but that doesn't seem useful.

**Comment by crackerbear** [comment]
Thanks it wasn't entirely obvious there was a beta version, but it's now working as expected.
