### ISSUE TITLE
So i used gw2 laucher earlier on this PC. 

### ISSUE THREAD

**Issue by Enrag3** [Healix/Gw2Launcher#49]
But after i stopped playing gw2 and came back i found out that gw2 laucher is now updated and has new features.(god bless your sould for the hard work btw) But now when i try to lauch an account it says failed.

**Comment by Healix** [comment]
Hover your mouse over the account that says failed and it should show a popup saying why. Generally failed launches are due to a problem with Local.dat - to force a re-check, right click the account > selected > update, then launch (normal).

**Comment by Enrag3** [comment]
Unknown User profile structure. But when i type in the credentials and press save it still doesnt work.

**Comment by Enrag3** [comment]
QUick background: My Appdata is moved from the default disc to my 1tb ssd. Idk if thats the case but it is how it is.

**Comment by Healix** [comment]
That error happens when %appdata% isn't located under %userprofile%. Where is your %appdata% located vs %userprofile% and how are you moving it? - you can enter those variables into the folder's address bar.

As a workaround, you can try changing the mode of Gw2Launcher to basic under Settings > Guild Wars 2 > Management, which doesn't have this check.

**Comment by Enrag3** [comment]
My Appdata is not located under my Userdata folder if you are asking that.
But as for workaround that indeed helped with my issue. It now works just fine. Thank you :)
