### ISSUE TITLE
Issues with just launching in the first placed, no successful launch yet

### ISSUE THREAD

**Issue by Pikachewie** [Healix/Gw2Launcher#5]
Whenever I try to login it says Last Used Failed, even though set up the right directory, have checked the email and password account multiple times. What's going on?

**Comment by Pikachewie** [comment]
Would like any help possible, and thank you for making this

**Comment by Healix** [comment]
Hover your mouse over it and it should give you more information on why it failed

**Comment by Healix** [comment]
Since you mentioned checking your email/password, are you relying on the automatically login to character select option? If so, that was disabled by ArenaNet yesterday and can no longer be used. You'll will need to setup each account with its own Local.dat file.

**Comment by Pikachewie** [comment]
Got it! So now an issue I have now  is " Unable to Open Archive File. Guild wars 2 is unable to access its archive Appdata\Roaming\Gw2laucnher\data\4\AppData\Roaming\Guild Wars 2\Local.dat" Please verify that this file is accessible and writable and that no other program is currently using it. Have had issues trying to make new local dat files that are recognized by the launch program but all it sees is the original one even though I made copies of local dat files in the folder.

**Comment by Pikachewie** [comment]
Never mind you are amazing, I got it all set up correctly. Is there anyway to donate to you for your work?

**Comment by Pikachewie** [comment]
And no I meant with real money. You're quite active on the forums and you made something that multiboxers can still use and I appreciate that a lot. You're giving other multiboxers something to use while ANET either ignores us or possibly makes a solution. And I'm surprised I'm the first to mention it.

**Comment by Healix** [comment]
For clarification, there is no need to copy/paste any Local.dat files in Windows. If you wanted to copy a specific Local.dat file, you'd do it under the "Local.dat" tab of the account, by clicking the "..." button and choosing to copy an existing file.

To make things simple, download and run the version I released on January 23 if you're not already using it. Hold the ALT key to show the add account button and click it (or right click an account > create a new account). Give this account a name and click OK to create it. This is how simple it can be to create a new account.

As for a video tutorial, I could, but since it's so simple to setup an account, I'll just add screenshots to the wiki page later:
https://github.com/Healix/Gw2Launcher/wiki/Getting-Started

**Comment by madyahoo** [comment]
ok the new version it's great .thanks you  for your works.

**Comment by Pikachewie** [comment]
hey Healix I have another issue, I have to keep inputting it all over again because it keeps saying "download failed!" please check your internet and try again (5)

**Comment by Kahsua** [comment]
Hey @Pikachewie, the local.data has to update. Just press right click on any account starter and select: All -> Update.
Each Launcher will start and update the specific Local.data. After that u can use it normaly.
