### ISSUE TITLE
Unable to launch 2 accounts

### ISSUE THREAD

**Issue by rickiezz** [Healix/Gw2Launcher#50]
When I use localized execution (full) and localized ui, I can not launch 2 accounts. The second just doesnt launch until the first one is closed.

Without localized execution they both launch fine, but then my addons do not work.

**Comment by Healix** [comment]
Using d912pxy? It was previously causing this problem. One of their updates a while back caused the game to stall while another client was active, since d912pxy was requiring write-access. Localized execution should fix that problem, but if it's happening again, they probably added more problems.

If you're not using d912pxy, figure out which addon is causing it by removing them 1 by 1.

If you are using it...

When using localized execution, you'll find a Gw2Launcher folder where GW2 is located. In this folder is a # for each account (created after the account is launched once) and in that folder is a virtual copy of your GW2 folder. Delete d912pxy from these # folders and replace it by copying the real d912pxy folder here.

---

As for why your addons don't work with it disabled, when launching multiple accounts, GW2 will change the location of its bin folder if it can't write to its default bin folder. Enabling localized CoherentUI forces this behavior, since GW2 can crash if multiple accounts try to use CoherentUI (the web browser used by the launcher and trading post) at the same time.

**Comment by rickiezz** [comment]
Amazing, this worked. 

Placing copying the actual bin folders made it work instantly.

If I may do a suggestion, put this on the helppage for addons :).

Thanks alot!!!
