### ISSUE TITLE
Can't remove page?

### ISSUE THREAD

**Issue by czokalapik** [Healix/Gw2Launcher#57]
It's very minor thing, but after reorganizing accounts I wanted to remove one of the empty pages I created, and I can't find where I can do it (if I can).

**Comment by Healix** [comment]
There is currently no way to remove an empty page. The number of pages is based on the last page used, so the only way to remove a page is by moving the last used page into it.

**Comment by czokalapik** [comment]
what do you mean "moving last page into it"?

**Comment by Healix** [comment]
On the last non-empty page, select all accounts, right click > selected > show on page > # + remove from current page

This will move all accounts on that page to the page you entered, and since the last page is now empty, it'll be removed, shrinking the total pages down to the new last non-empty page.

**Comment by czokalapik** [comment]
When I wrote my last comment I realized there is no page remove button, because there is no add button, so there is always one additional empty page. sorry for being a stupid moron ;)
