### ISSUE TITLE
highlight active gw2 window

### ISSUE THREAD

**Issue by pro0digy** [Healix/Gw2Launcher#7]
Is it possible to highlight active gw2 window? It would help switching between accounts fast #

**Comment by Healix** [comment]
What do you mean by highlight? Color the buttons of active accounts differently in Gw2Launcher, rather than just showing "active" in green as it currently does?

If you click an active account in Gw2Launcher, note that by default it will switch to that window. If you want to use Gw2Launcher to help switch between accounts, you could choose to sort (right click > sort by) your accounts by last used so that they're at the top, and set Gw2Launcher to be on top of other windows (settings > general > show on top). If you need help recognizing which window is which account, you can also choose to change the title of GW2's window (settings > general / windows > caption) to include the account's name for example. This will also allow you to more easily switch accounts using WindowsKey+Tab (or ALT+Tab).

**Comment by magnapeccatrix** [comment]
@pro0digy

Click on accounts name at GW2Launcher window, it will focus on related account's window.

**Comment by magnapeccatrix** [comment]
I understood now you actually meant the highlighting on Game Instance window. Based on your previous entry "Launchbuddy has an instance manager, which would highlight focused GW2 **window**" the word window here led to me think you meant client window rather than the game instance mini panel. 

I've recorded a gif for Healix to see how it functions, you (OP) want this highlighting to be implemented on GW2Launcher window. Would be useful in my opinion, as well.

![euqxids5kc](https://user-images.githubusercontent.com/15203877/51927375-7dc45a00-2404-11e9-8e5e-3c4c0b89c8c1.gif)

**Comment by pro0digy** [comment]
exactly. sorry for my bad english

**Comment by Healix** [comment]
I've added an account bar in the recent release, which will by default appear in the vertical list format like the above, but all accounts will be shown for display purposes, which you can turn off under its sorting. It can also be snapped to the edges of the screen if you want it more like a taskbar.

The highlighting shown above is just LaunchBuddy keeping the last account you clicked selected. I've included the option to highlight the account, but I've based it on actually focusing the window, so it'll be highlighted whether you click it in Gw2Launcher or alt-tab to it.

If you want the bar, it can be enabled under Settings > Tools > Account bar

If you just wanted the highlight for the main window, it can be enabled under Settings > Style

**Comment by pro0digy** [comment]
Thank you so much! Works like a charm.
