### ISSUE TITLE
problem retaining sound settings

### ISSUE THREAD

**Issue by BobRichmond** [Healix/Gw2Launcher#8]
I am usually listening to streams or listening/talking in Discord while playing GW2. For this reason I would want GW2 to launch with master volume very low. I just started using your app to launch my 4 accounts and have turned down all the volumes to what I want them in the game options. However next time I launch them the volumes are back up to max. Is there any way I can retain those settings like they are naturally retained in GW2?

**Comment by Healix** [comment]
If you want to be able to modify your in-game settings, you need to launch the account normally by right clicking it > selected > launch (normal). This is because GW2 is in read-only mode when it allows multiple clients to be opened simultaneously.

Alternatively, Gw2Launcher supports controlling the volume. If you want to change the volume on every account, simply right click any account > settings > launch options > volume, or for a specific account, it's right click > edit > ...

**Comment by BobRichmond** [comment]
Thanks for your quick reply, but I do have 1 question. If you use the second method does it actually set the game master volume or Windows volume? If it is the latter would that mess with the volume I get from Discord or Twitch? I will be using the first method, so an answer to this question is just for my education in case I have to answer questions to the many people I am suggesting this app to.

**Comment by Healix** [comment]
It's the equivalent of opening the volume mixer in Windows and changing the volume specifically for that instance of GW2. It won't affect the volume of anything else.

**Comment by BobRichmond** [comment]
Once again thanks for the quick reply. I do have another minor issue that I will be gathering more information on for you. When I go to open a second account I frequently get a GW2 crash box. If I close the box and try again it has always worked. I did a quick check of the crash details earlier when this happened and it said something like unable to open Coherent DLL.
