### ISSUE TITLE
Remembering client window position when using DX11

### ISSUE THREAD

**Issue by nknwn** [Healix/Gw2Launcher#83]
While using DX9, we can move client windows in different locations/corners of the screen, it will be saved and always opened in said location while DX9 is active.
With DX11, each client that has it enabled (or if enabled for all from the main settings) will open in the top left corner of the main display and not only that but it's a bit higher making the title bar of the window hidden over the top of the display.
Is this something that Gw2Launcher handles or it's from the OS ?

**Comment by Healix** [comment]
If the windowed mode option is configured in Gw2Launcher (Edit > Launch options), Gw2Launcher handles it.

GW2 can also save its own position. DX9 and DX11 have separate positions, which is why enabling DX11 moves the window to the top/left 0,0. Note accounts launched through Gw2Launcher are by default in read-only mode to allow multiple clients to launch simultaneously, so if you want GW2 to save its position, you have to right-click the account > Selected > Launch (normal). Once GW2 loads its window, move and resize it, then exit to save it. The DX11 window is a little buggy however and may not save correctly.

**Comment by nknwn** [comment]
I did launch them in normal mode but it's never saving the position in DX11

**Comment by Healix** [comment]
Multiple screens? I did a few tests and DX11 saved positioning is locked to the primary screen - if the window is not (mostly) on the primary screen, it will revert to the top/left 0,0.

**Comment by nknwn** [comment]
Yes multiple screens. Have one main account windowed full-screen on primary display and 4 clients each snapped to the corners of secondary display occupying a quarter of the screen each. This works without any problems with DX9 but DX11 just doesn't want to work right

**Comment by Healix** [comment]
You'll have to use the windowed option in Gw2Launcher for other screens, or not use DX11 / wait for GW2 to fix the bug.
