### ISSUE TITLE
GW2 crashing on opening second account

### ISSUE THREAD

**Issue by BobRichmond** [Healix/Gw2Launcher#9]
*--> Crash <--*
Assertion: Launcher: Browser crashed 
File: ..\..\..\Game\Launcher\LauncherCoherent.cpp(2523)
App: Gw2-64.exe 
Pid: 6612
BaseAddr: 00007FF76A4C0000
ProgramId: 101
Build: 94892
When: 2019-01-28T00:53:58Z 2019-01-27T19:53:58-05:00
Uptime:   0 days  0:00:04
Flags: 0
------------------------------------------------------------------
I had an account opened and sitting in Royal Terrace. Alt-tabbbed out and clicked on a second account in the launcher. Before the GW2 login window came up, a GW2 crash window came up with the above details. I copied the above details, closed the crash window, and then clicked on the same account in the launcher a second time and all worked as it should. This is not a big problem and does not happen every time, but thought you would like to know about it.

**Comment by Healix** [comment]
GW2 uses CoherentUI_Host.exe to render the launcher. If this process exits for any reason, it'll cause that crash.

Since this apparently isn't happening on your first launch, note that CoherentUI is stored under GW2's bin folder, but if it's already being used, it's copied to a cache folder. For Gw2Launcher specifically, the gw2cache folders can be found under %appdata%/Gw2Launcher/data/temp/. 

Try disabling your security software to confirm it's not interfering / whitelist the above.

Software that hooks into the graphics can also cause CoherentUI to actually crash. Check lower in the crash log under the DLL list, which may give you an idea. Overlays, Discord, MSI Afterburner / RivaTuner and graphics enhancers/mods are the usual ones for example.

**Comment by magnapeccatrix** [comment]
Hello, If I try to launch three accounts at same time (Fast click Play 3 times) one or two clients crash immediately before getting to character select screen. This started to happen few days ago after some small updates to the game.

*--> Crash <--*
Assertion: Failed to start Coherent host 
File: ..\..\..\Engine\ArenaWeb\CoherentUi\AwCohContext.cpp(331)
App: Gw2-64.exe 
Pid: 10544
BaseAddr: 00007FF761600000
ProgramId: 101
Build: 94892
When: 2019-01-29T02:14:38Z 2019-01-29T05:14:38+03:00
Uptime:   0 days  0:00:15
Flags: 0

*--> Error Logs <--*
WebBrowser: Skipping file CoherentUI_Host.exe due to sharing violation
WebBrowser: Skipping file CoherentUI64.dll due to sharing violation
WebBrowser: failed to create icudt.dll, 5
WebBrowser: failed to create ffmpegsumo.dll, 5
WebBrowser: Skipping file CoherentUI64.dll due to sharing violation
Failed to start Coherent host: (OSError=32, Error=Could not start Coherent UI host process.)

**Comment by magnapeccatrix** [comment]
Thank you for answer Healix :) i think that's the issue, I am going to beta version today and see how it is!

**Comment by magnapeccatrix** [comment]
@Healix, this version seems to fix issue, it just works seamless and all accounts proceeds to character select screen properly.

Thank you!

**Comment by Healix** [comment]
CoherentUI shouldn't be a problem in the recent release. There was another problem I caught, though it was very rare. In short, GW2 could fail to create CoherentUI if it was trying to make too many copies at the same time.

There's a new option (Settings > General > Launching > Localized account execution) that will give each account its own copy of the bin folder. Normally GW2 will copy the bin folder if its already in use, once on launch and again when you click play, so this also ends up saving you ~83 MB per launch, in additional to slightly reducing the initial load and allowing you to have custom DLLs per account.

**Comment by BobRichmond** [comment]
The most recent release seems to have solved my crashing the first time I open a second account. Thanks for your continuous work on this. Also love that you changed the icon for the launcher, as now there are multiple GW2 icons on the task bar when you have multiple accounts open.

**Comment by magnapeccatrix** [comment]
Healix, thank you for your tremendous work, lots of new features are in the launcher. They are all great!

However there is one thing I noticed, if we use the Localized account execution, I noticed each account is using full .dat file size in their own paths. But they are actually not, because I have GW2 installed on a nearly full 120GB drive and In this case all these 3 accounts folders are alone reporting 121GB used space. In this case I should have around 210GB data inside the 120 GB drive but Windows reports disk space correctly.

![gw222](https://user-images.githubusercontent.com/15203877/53327065-152fa680-38f8-11e9-8ad0-878896ec9639.png)

**Comment by Healix** [comment]
Those are called hard links. It allows for one file to have multiple filenames, so if you were to modify the text file in there for example, you'll notice that they've all changed. They don't actually take up the shown amount of disk space, as you've already noted. Explorer just shows it like that because that's how it works; they're fake files.

The only real files in those folders are some of the DLLs in the bin folder (~13 MB: d3dc, ffmpeg, icudt, libE, libG), since they require exclusive locks, otherwise they're all copied to the cache folder (~48 MB) up to 2 times per launch.
